server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${SCHEMA_NAME}?noAccessToProcedureBodies=true
    username: tempManUser
    password: ${DB_USER_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
  file:
    name: /proj/Temp-Man-DEV/logs/trace.log
  logback:
    rollingpolicy:
      file-name-pattern: /proj/Temp-Man-DEV/logs/logbacks/tempMan-%d{yyyy-MM-dd}/%i.log
